### ISSUE TITLE
Model 2R 179 - Experiment 5 issue

### ISSUE THREAD

**Issue by locivass** [McKibbin-Software-Group/issues#11]
Hi team

Using the practice 2R model (version 179) it looks like the simulation "Experiment 5" has an issue calling particular years in one of the date files. The code appears to finish it's run but doesn't produce any outputs. Thanks for your help!

Error message and console log are below:

@locivass ➜ /workspace/user_data (main) $ /usr/local/bin/python /workspace/user_data/2R/179/python/run_fast_experiment_5.py
2024-08-06 01:08:10,706 - INFO - model_constants.py - Line:75 - Saving results and logs to /workspace/user_data/results/2R/179/run_fast_experiment_5.
2024-08-06 01:08:10,707 - INFO - run_fast_experiment_5.py - Line:84 - Updating the values in the controls file, controls.csv from 2018 onwards.
2024-08-06 01:08:10,707 - INFO - run_fast_experiment_5.py - Line:123 - Loading previously generated baseline projections from /workspace/user_data/results/2R/179/run_fast_experiment_5/baseline_projections.pickle
2024-08-06 01:08:10,731 - INFO - run_fast_experiment_5.py - Line:127 - Loaded the baseline projections
2024-08-06 01:08:10,789 - INFO - simulation_layer.py - Line:55 - Generating the controls_layer simulation layer projections.
2024-08-06 01:08:11,663 - INFO - simulation_layer.py - Line:87 - The controls_layer simulation layer projections have been generated.
2024-08-06 01:08:11,664 - INFO - simulation_runner.py - Line:186 - Added controls_layer simulation layer to projections from 2018.
2024-08-06 01:08:11,664 - INFO - simulation_runner.py - Line:192 - The run has completed.
Traceback (most recent call last):
  File "/workspace/user_data/2R/179/python/run_fast_experiment_5.py", line 256, in <module>
    solver_results = least_squares(fun=objective_function, x0=start_x, xtol=1e-2, ftol=1e-2)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.12/site-packages/scipy/optimize/_lsq/least_squares.py", line 832, in least_squares
    f0 = fun_wrapped(x0)
         ^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.12/site-packages/scipy/optimize/_lsq/least_squares.py", line 830, in fun_wrapped
    return np.atleast_1d(fun(x, *args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/user_data/2R/179/python/run_fast_experiment_5.py", line 237, in objective_function
    runner.final_projections.publishable_projections.loc[
  File "/home/vscode/.local/lib/python3.12/site-packages/pandas/core/indexing.py", line 1184, in __getitem__
    return self._getitem_tuple(key)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.12/site-packages/pandas/core/indexing.py", line 1375, in _getitem_tuple
    return self._multi_take(tup)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.12/site-packages/pandas/core/indexing.py", line 1327, in _multi_take
    axis: self._get_listlike_indexer(key, axis)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.12/site-packages/pandas/core/indexing.py", line 1558, in _get_listlike_indexer
    keyarr, indexer = ax._get_indexer_strict(key, axis_name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 6200, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "/home/vscode/.local/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 6249, in _raise_if_missing
    raise KeyError(f"None of [{key}] are in the [{axis_name}]")
KeyError: "None of [Index(['2090', '2091', '2092', '2093', '2094', '2095', '2096', '2097', '2098', '2099', '2100'], dtype='object')] are in the [columns]"

**Comment by shuetrim** [comment]
Hi Locivass

apologies for the sluggish response. Too much snorkelling and scuba diving over here in WA. As compensation, here is one of the better slugs I came across.

![GOPR5130](https://github.com/user-attachments/assets/7979318f-ab12-43e4-b768-295f1432aeb3)

I cannot replicate your problem at the moment so we will have to put a bit of the onus on you to help with debugging what is going on.

The log messages can be quite confusing but they do tell us some useful things:

1. There is a line that indicates: 

Loading previously generated baseline projections from /workspace/user_data/results/2R/179/run_fast_experiment_5/baseline_projections.pickle

That shows you have generated the baseline projections and shared them correctly which is a good first step.

2. The line:

File "/workspace/user_data/2R/179/python/run_fast_experiment_5.py", line 256, in
solver_results = least_squares(fun=objective_function, x0=start_x, xtol=1e-2, ftol=1e-2)

shows that the problem happens when  you are running the least-squares optimisation. It evaluates the objective function and things go wrong at line 237 of the script:

runner.final_projections.publishable_projections.loc[

What we are doing there is accessing the publishable version of the final projections dataframe, produced by the simulation runner. There seems to be a problem with the values in the targets.columns compared to the columns of that publishable final projections dataframe.

Try adding, at line 234 the following debugging log commands:

    logging.debug(targets.columns)
    logging.debug(runner.final_projections.publishable_projections.columns)
    exit(9)

That will show the key information and then stop execution.

The problems is that there are some values in the targets columns that are not in the publishable projections.  My guess is that your publishable projections end in 2080 or 2070.

To fix the problem, remove the debug code you added and then you can do one of two alternative things:

a. Change the years in the targets.csv file to end in 2080 or whatever is the last year in your publishable projections; or

b. make sure that the configuration file (configuration2R179.csv) contains the following settings:
LastProjectionYear,2150,The last year to generate projections for.
LastPublishableProjectionYear,2100,The last year to generate projections for that will be published.

Then delete all of the run_fast_baseline results folder and rerun the fast baseline. Then rerun  experiment 5.  I hope that works for you.

Regards

Geoff

**Comment by locivass** [comment]
Hi Geoff

That's an impressive looking slug! Hope the snorkelling/diving is going well.

I ran the debugging comands as instructed, and you're right my publishable projections end in 2080, whereas the target years are specified over 2090-2100. 

I implemented option a and can confirm that has worked.

Thanks again!

Lachlan
